# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the chartsMonorepo branch
on:
  push:
    branches: [ chartsMonorepo ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: git-filter-repo
      uses: tarrow/git-repo-filter-docker-action@v26
      with:
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
        targetOrg: tarrow
        targetRepo: Changes-clone
        targetBranch: main
        filterArguments: >-
          --path=lib/includes/changes/
          --path=lib/includes/Changes/  
          --path=lib/tests/phpunit/changes/ 
          --path=lib/tests/phpunit/Changes/ 
          --path lib/packages/wikibase/changes/
          --path .mailmap
          --path-rename=lib/includes/changes:src
          --path-rename=lib/includes/Changes:src
          --path-rename=lib/tests/phpunit/changes:tests
          --path-rename=lib/tests/phpunit/Changes:tests
          --path-rename lib/packages/wikibase/changes/:
          --message-callback 'return re.sub(b"^changes: ", b"", message)'
